name: Maven Package
on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Publish package
      run: mvn --batch-mode depoly
      env:
        GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}
