server:
  port: 8089
spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    contexts: postgres
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 123

  jpa:
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL10Dialect
#    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: INFO

app:
  allowed-origins:
    http://41.38.83.137:8060,http://localhost:4200

  jwt:
    token:
      expiration-in-ms: 120000
    refresh:
      expiration-in-ms: 3600000
    secret: ElectionEgypt2022VeryVeryVeryVeryVeryVerySecretKey